apiVersion: apps/v1
kind: Deployment
metadata:
  name: cricket-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cricket-frontend
  template:
    metadata:
      labels:
        app: cricket-frontend
    spec:
      containers:
        - name: cricket-frontend
          image: cricket-frontend:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 80