apiVersion: apps/v1
kind: Deployment
metadata:
  name: cricket-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cricket-api
  template:
    metadata:
      labels:
        app: cricket-api
    spec:
      containers:
        - name: cricket-api
          image: cricket-api:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 5000