apiVersion: v1
kind: Service
metadata:
  name: cricket-api-service
spec:
  selector:
    app: cricket-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort